#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

version: 2.1

executors:
  jdk-executor:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  sbt_verify:
    parameters:
      daml_sdk_version:
        type: string
    executor: jdk-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "build.sbt" }}
            - m2
      - run:
          command: |
            ./scripts/install-daml.sh << parameters.daml_sdk_version >>
            export PATH=$PATH:~/.daml/bin
            sbt verify packageAll
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sbt
            - ~/.daml
          key: m2-{{ checksum "build.sbt" }}
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_refapps_func_test master --logging.level.com.synopsys.integration=DEBUG

workflows:
  version: 2
  build_and_test:
    jobs:
      - sbt_verify:
          daml_sdk_version: "0.13.13"
          context: blackduck
